# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = "fw_pull"
py_version = "3.6"
version = "0.1.0"


[tool.pyflow.scripts]


[tool.pyflow.dependencies]
requests = "^2.23.0"
selenium = "^3.141.0"
bs4 = "^0.0.1"


[tool.pyflow.dev-dependencies]

