#!/usr/bin/env python3

import re
import sys

from bs4 import BeautifulSoup

from selenium import webdriver 
from selenium.webdriver.common.by import By 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support import expected_conditions as EC 
from selenium.webdriver.common.action_chains import ActionChains


def get_dell(driver, model):
    timeout = 20
    
    url = "https://www.dell.com/support/home/us/en/04/product-support/product/poweredge-" + model.lower() + "/drivers"
    try:
        driver.get(url)
        
        body = driver.find_element_by_xpath("//option[@label='Support']")
        
        action = ActionChains(driver)
        action.move_to_element(body).perform()
        
        #search = driver.find_element_by_xpath("//input[@id='keyword']")
        #search.clear()
        #search.send_keys("bios")
        #search.send_keys(Keys.RETURN)

        WebDriverWait(driver, timeout).until(
            EC.visibility_of_element_located(
                (By.XPATH, "//select[@id='operating-system']")
            )
        )

        os_sort = driver.find_element_by_xpath("//select[@id='operating-system']")
        os_sort.click()

        WebDriverWait(driver, timeout).until(
            EC.visibility_of_element_located(
                (By.XPATH, "//option[@value='NAA']")
            )
        )

        bios_select = driver.find_element_by_xpath("//option[@value='NAA']")
        bios_select.click()

        WebDriverWait(driver, timeout).until(
            EC.visibility_of_element_located(
                (By.XPATH,"//select[@id='ddl-category']")
            )
        )
        cat_select = driver.find_element_by_xpath("//select[@id='ddl-category']")
        cat_select.click()

        cat_bios_sel = driver.find_element_by_xpath("//option[@value='BI']")
        cat_bios_sel.click()

        source = BeautifulSoup(driver.page_source, 'html.parser')
    
    except Exception as e:
        print(e)
        sys.exit(1)
        driver.quit()
    
    list_items = source.find_all('td')
    
    ver = re.compile("Version (\d+\.\d+(\.\d+)?)")
    
    for item in list_items:
        match = ver.search(item.text)
        if match:
            print(match.group(1))


def dell_model(name):
    return name.strip().split()[1].lower()


def main():
    options = Options()
    #options.headless = True
    
    try:
        driver = webdriver.Firefox(options=options)
    except:
        print("Failed to initiate web driver")
        sys.exit(1)
        
    models = ['Poweredge R630 ', ' Poweredge R330', 'Poweredge R730', 'Poweredge R930']
    
    for model in models:
        get_dell(driver, dell_model(model))
    
    driver.quit()


if __name__ == '__main__':
    main()
